db.getCollection("rocketchat_avatars").insert({
  _id: "MKBNfes8gxMXWJ92Q",
  userId: "pigeon.cat",
  type: "image/png",
  size: NumberInt(15150),
  store: "GridFS:Avatars",
  _updatedAt: new Date(1584022383071),
  instanceId: "DazcJz4ePrpaT9fhB",
  name: "pigeon.cat",
  complete: true,
  etag: "epCf7uvbjuLqxn5ug",
  path: "/ufs/GridFS:Avatars/MKBNfes8gxMXWJ92Q/undefined",
  progress: NumberInt(1),
  token: "b8AB381B99",
  uploadedAt: new Date(1584022383291),
  uploading: false,
  url: "http://localhost:3000/ufs/GridFS:Avatars/MKBNfes8gxMXWJ92Q/undefined",
});
