import { StyleSheet } from "react-native";

export default StyleSheet.create({
  topBar: {
    backgroundColor: "white",
    height: 140,
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
    padding: 20,
  },
  image: {
    width: "100%",
    height: 400,
    justifyContent: "center",
    alignItems: "center",
  },
  icon: {
    alignItems: "center",
    justifyContent: "center",
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#e20e30",
    marginTop: 250,
  },
  bottomBar: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: "white",
    flex: 1,
  },
  title: {
    color: "#000000",
    fontSize: 40,
  },
  subText: {
    color: "#000f00",
    fontSize: 16,
  },
  iconImg: {
    height: 38,
    width: 38,
    alignSelf: "center",
  },
  iconImgAnswer: {
    height: 30,
    width: 30,
    alignSelf: "center",
  },
  btnStopCall: {
    height: 65,
    width: 65,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 32,
    backgroundColor: "#FF0000",
    position: "absolute",
    bottom: 160,
    left: "40%",
    zIndex: 1,
  },
  btnActionEnd: {
    height: 75,
    width: 75,
    flexDirection: "row",
    justifyContent: "center",
    backgroundColor: "#FF0000",
    alignItems: "center",
    borderRadius: 50,
  },
  btnActionAccept: {
    height: 75,
    width: 75,
    flexDirection: "row",
    justifyContent: "center",
    backgroundColor: "#00FF00",
    alignItems: "center",
    borderRadius: 50,
  },
  shadow: {
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.34,
    shadowRadius: 6.27,
    elevation: 10,
  },
});